# Generated by Django 5.2.5 on 2025-08-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
